In [1]:
import pandas as pd 
import pandera as pa

In [5]:
dataframe = pd.read_csv("ocorrencia20102020copia - Copia EDITADA.csv" , sep="\t",parse_dates=['ocorrencia_dia'])
dataframe

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,Unnamed: 9,Unnamed: 10
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,2010-03-01,12:00:00,0,NaN,NaN
1,40349,40349,INCIDENTE,BEL�M,PA,SBBE,2010-03-01,11:05:00,0,NaN,NaN
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-03-01,03:00:00,0,NaN,NaN
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,2010-04-01,17:30:00,0,NaN,NaN
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-05-01,19:25:00,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0,NaN,NaN
5748,79757,79757,INCIDENTE GRAVE,LAGOA DA CONFUS�O,TO,****,2020-12-30,18:30:00,0,NaN,NaN
5749,79802,79802,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2020-12-30,00:54:00,0,NaN,NaN
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,****,2020-12-31,09:00:00,0,NaN,NaN
5751,79844,79844,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2020-12-31,13:24:00,0,NaN,NaN

In [3]:
dataframe.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
Unnamed: 9                         float64
Unnamed: 10                        float64
dtype: object

In [4]:
dataframe.ocorrencia_dia

0      2010-03-01
1      2010-03-01
2      2010-03-01
3      2010-04-01
4      2010-05-01
          ...
5747   2020-12-29
5748   2020-12-30
5749   2020-12-30
5750   2020-12-31
5751   2020-12-31
Name: ocorrencia_dia, Length: 5752, dtype: datetime64[ns]

In [5]:
dataframe.ocorrencia_dia.dt.month

0        3
1        3
2        3
3        4
4        5
        ..
5747    12
5748    12
5749    12
5750    12
5751    12
Name: ocorrencia_dia, Length: 5752, dtype: int64

In [15]:
datafdataframe = pd.read_csv("ocorrencia20102020copia - Copia EDITADA.csv" , sep="\t",parse_dates=['ocorrencia_dia'], dayfirst=True)
datafdataframe.tail(10)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,Unnamed: 9,Unnamed: 10
5742,79800,79800,INCIDENTE,S�O PAULO,SP,SBMT,2020-12-28,10:15:00,0,NaN,NaN
5743,79824,79824,ACIDENTE,RIO PARANA�BA,MG,SNRP,2020-12-28,17:00:00,0,NaN,NaN
5744,79753,79753,INCIDENTE GRAVE,GOIATUBA,GO,****,2020-12-29,12:00:00,0,NaN,NaN
5745,79755,79755,ACIDENTE,MATO RICO,PR,****,2020-12-29,10:30:00,0,NaN,NaN
5746,79769,79769,INCIDENTE GRAVE,MANOEL URBANO,AC,SIMB,2020-12-29,18:30:00,0,NaN,NaN
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0,NaN,NaN
5748,79757,79757,INCIDENTE GRAVE,LAGOA DA CONFUS�O,TO,****,2020-12-30,18:30:00,0,NaN,NaN
5749,79802,79802,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2020-12-30,00:54:00,0,NaN,NaN
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,****,2020-12-31,09:00:00,0,NaN,NaN
5751,79844,79844,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2020-12-31,13:24:00,0,NaN,NaN

dataframe.dtypes
dataframe.ocorrencia_dia.dt.month

In [9]:
dataframe.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
Unnamed: 9                         float64
Unnamed: 10                        float64
dtype: object

pip install pandera

In [19]:
schema = pa.DataFrameSchema(
    columns = {
        "codigo_ocorrencia": pa.Column(pa.Int),
        "codigo_ocorrencia2": pa.Column(pa.Int),
        "ocorrencia_classificacao": pa.Column(pa.String),
        "ocorrencia_cidade ": pa.Column(pa.String),
        "ocorrencia_uf": pa.Column(pa.String, pa.Check.str_lenght(2,2)),
        "ocorrencia_aerodromo": pa.Column(pa.String),
        "ocorrencia_dia": pa.Column(pa.DateTime),
        "ocorrencia_hora": pa.Column(pa.String, pa_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'), nullable=True),
        "total_recomendacoes": pa.Column(pa.Int)
        
,        
        
    }
)

AttributeError: '<class 'pandera.checks.Check'>' object has no attribute 'str_lenght'. Make sure any custom checks have been registered using the extensions api.

In [20]:
schema.validate(dataframe)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,Unnamed: 9,Unnamed: 10
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,2010-03-01,12:00:00,0,NaN,NaN
1,40349,40349,INCIDENTE,BEL�M,PA,SBBE,2010-03-01,11:05:00,0,NaN,NaN
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-03-01,03:00:00,0,NaN,NaN
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,2010-04-01,17:30:00,0,NaN,NaN
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-05-01,19:25:00,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0,NaN,NaN
5748,79757,79757,INCIDENTE GRAVE,LAGOA DA CONFUS�O,TO,****,2020-12-30,18:30:00,0,NaN,NaN
5749,79802,79802,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2020-12-30,00:54:00,0,NaN,NaN
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,****,2020-12-31,09:00:00,0,NaN,NaN
5751,79844,79844,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2020-12-31,13:24:00,0,NaN,NaN

In [21]:
schema.validate(dataframe)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,Unnamed: 9,Unnamed: 10
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,2010-03-01,12:00:00,0,NaN,NaN
1,40349,40349,INCIDENTE,BEL�M,PA,SBBE,2010-03-01,11:05:00,0,NaN,NaN
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-03-01,03:00:00,0,NaN,NaN
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,2010-04-01,17:30:00,0,NaN,NaN
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-05-01,19:25:00,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0,NaN,NaN
5748,79757,79757,INCIDENTE GRAVE,LAGOA DA CONFUS�O,TO,****,2020-12-30,18:30:00,0,NaN,NaN
5749,79802,79802,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2020-12-30,00:54:00,0,NaN,NaN
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,****,2020-12-31,09:00:00,0,NaN,NaN
5751,79844,79844,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2020-12-31,13:24:00,0,NaN,NaN